# Generated by Django 5.1 on 2024-09-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_epi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epi',
            name='validade_uso',
        ),
    ]
