# Generated by Django 5.1 on 2024-09-28 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_remove_epi_validade_uso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateField()),
                ('status', models.CharField(choices=[(1, 'Emprestado'), (2, 'Em uso'), (3, 'Fornecido'), (4, 'Devolvido'), (5, 'Danificado'), (6, 'Perdido')], default=1, max_length=10)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='site_app.colaborador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='site_app.epi')),
            ],
        ),
    ]
